### ISSUE TITLE
do not display `history` in charter previews

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#104]
(examples where it displays: https://charters-qa.bodleian.ox.ac.uk/?f%5Bms_collection_s%5D%5B%5D=Suffolk&f%5Btype%5D%5B%5D=charter&page=16&per_page=200) -- apparently because of the format of the `history` selection with an `acquistion` element and no `provenance` elements (which can be changed in the data, but might be useful to change whatever is causing the display to avoid future issues)

**Comment by Slange-Mhath** [comment]
Kind of, the problem here is again that Phyiscal Description is not in the data (because it probably does not have one). Regex is super powerful so my current quick fix solution would be that I adjust the regex to check if Physical Description is somewhere in the data, and if so use that as ending for the preview text (not including) or if its not in the data use History as ending (not including). While that will probably work it can cause side effects. Another "problem" with regex is that it can potentially slow things down a bit - my long term solution would be that I open another issue discussing how we could use another preview field in the data which we'd need to create in the data once and can then just display in blacklight. For now though, I just adjust the regex.

**Comment by Slange-Mhath** [comment]
Thats the short term fix: https://gitlab.bodleian.ox.ac.uk/TEI-consolidation/charters-catalogue-search/-/commit/a48188f3d4206ba60b68533f831e8737906ba2fa 

And the long term fix I'd propose for sometime soon: https://github.com/bodleian/charters/issues/106
